server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html

pixabay:
  key: ${PIXABAY_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    com.services: INFO